app/urls.py
from django.conf.urls import url

from app import views

urlpatterns= [

    url(r'^home/', views.home,name='home'),
    # url(r'^market/', views.market,name='marketbase'),
url(r'^market/', views.market,name='market'),
# url(r'^market/(\d+)/', views.market,name='market'),
url(r'^cart/', views.cart,name='cart'),
url(r'^mine/', views.mine,name='mine'),
url(r'^login/', views.login,name='login'),
url(r'^register/', views.register,name='register'),
url(r'^logout/', views.logout,name='logout'),



]

axf/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
url(r'^axf/', include('app.urls',namespace='axf')),

]

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}

        {% endblock %}
    </title>

<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
 <link href="https://cdn.bootcss.com/twitter-bootstrap/3.3.7/css/bootstrap.css" rel="stylesheet">

<link rel="stylesheet" href="{% static 'base/css/reset.css' %} ">
    <link rel="stylesheet" href="{% static 'base/css/base.css' %} ">
    {% block extcss %}

    {% endblock %}

</head>
<body>

{% block body %}
    {% block header %}
        <header>爱鲜蜂</header>
    {#导航#}
    {% endblock %}

    <div class="hidescroll">
    <div id="content">
        {% block content %}


    {#主体#}
    {% endblock %}

    </div>



    </div>


      {% block footer %}
          <footer>
              <a href="{% url 'axf:home' %}" class="home">
                  <dl>
                      <dt>
                          <span></span>
                      </dt>
                      <dd>首页</dd>
                  </dl>
              </a>

             <a href="{% url 'axf:market' %}" class="market">
                  <dl>
                      <dt>
                          <span></span>
                      </dt>
                      <dd>闪购超市</dd>
                  </dl>
              </a>

           <a href="{% url 'axf:cart' %}" class="cart">
                  <dl>
                      <dt>
                          <span></span>
                      </dt>
                      <dd>购物车</dd>
                  </dl>
              </a>
           <a href="{% url 'axf:mine' %}" class="mine">
                  <dl>
                      <dt>
                          <span></span>
                      </dt>
                      <dd>我的</dd>
                  </dl>
              </a>
          </footer>

    {#底部#}
    {% endblock %}

{% endblock %}
<script src="{% static 'base/js/jquery.min.js' %}"></script>
<script src="{% static 'base/js/base.js' %}"></script>
{% block extjs %}

{% endblock %}


</body>
</html>